// Generated by CoffeeScript 1.3.3

window.onload = function() {
  var change_mode, clear, create, get, mode, name, named, right, say, say_action, saying, socket, topic_list, topic_store, topics;
  socket = io.connect('http://localhost:8000/chat');
  socket.on('need-refresh', function() {
    return location.reload();
  });
  socket.on('ready', function() {
    return console.log('ready');
  });
  window.focus();
  named = false;
  saying = false;
  mode = '';
  get = function(id) {
    return document.getElementById(id);
  };
  right = get('right');
  topics = get('topics');
  create = get('create');
  say = get('say');
  name = get('name');
  clear = get('clear');
  change_mode = function(item) {
    if (item !== mode) {
      mode = item;
      return say.style.color = (item === 'say' ? 'hsl(0,0%,50%)' : 'hsl(0,0%,80%)');
    }
  };
  topic_list = [];
  topic_store = {};
  say_action = function() {
    return change_mode('say');
  };
  topics.onclick = function() {
    var item, _i, _len, _results;
    if (mode !== 'topics') {
      change_mode('topics');
      _results = [];
      for (_i = 0, _len = topic_list.length; _i < _len; _i++) {
        item = topic_list[_i];
        _results.push(log(item));
      }
      return _results;
    }
  };
  create.onclick = function() {
    var create_box, create_msg, create_send;
    if (mode !== 'create') {
      change_mode('create');
      right.innerHTML = '<div id="create_msg">Input A Name: (5 < Length < 20)</div>\
        <textarea id="create_box"></textarea>\
        <div id="create_send">Waiting</div>';
      create_msg = get('create_msg');
      create_box = get('create_box');
      create_send = get('create_send');
      create_box.focus();
      return create_box.oninput = function() {
        if (create_box.value.length < 6) {
          create_msg.innerText = 'Add More Words to be a Topic:';
          create_send.innerText = 'Waiting';
          create_send.onclick = function() {};
          return create_send.onkeydown = function() {};
        } else if (create_box.value.length > 40) {
          create_msg.innerText = 'The Title Contains too many Words..';
          create_send.innerText = 'Waiting';
          create_send.onclick = function() {};
          return create_send.onkeydown = function() {};
        } else {
          create_msg.innerText = 'Right Length now';
          create_send.innerText = 'Send';
          create_send.onclick = function() {
            socket.emit('add-topic', create_box.value);
            create_msg.innerText = 'OK, You\'ve Sent the Topic Successfully';
            create_send.innerText = 'Sent';
            return create_send.onclick = function() {};
          };
          return create_send.onkeydown = function(e) {
            if (e.keyCode === 13) {
              create_send.onclick();
              return false;
            }
          };
        }
      };
    }
  };
  say.onclick = function() {
    if (mode === 'say') {
      return say_action();
    }
  };
  (name.onclick = function() {
    var name_box, name_msg, name_send;
    if (mode !== 'name') {
      change_mode('name');
      right.innerHTML = '<div id="name_msg">Add a Topic here: (5 < Length < 40)</div>\
        <textarea id="name_box"></textarea>\
        <div id="name_send">Waiting</div>';
      name_msg = get('name_msg');
      name_box = get('name_box');
      name_send = get('name_send');
      name_box.focus();
      return name_box.oninput = function() {
        if (name_box.value.length < 2) {
          name_msg.innerText = 'Too Short';
          name_send.innerText = 'Waiting';
          name_send.onclick = function() {};
          return name_box.onkeydown = function() {};
        } else if (name_box.value.length > 20) {
          name_msg.innerText = 'Too Long now..';
          name_send.innerText = 'Waiting';
          name_send.onclick = function() {};
          return name_box.onkeydown = function() {};
        } else {
          name_msg.innerText = 'This name should be OK';
          name_send.innerText = 'Send';
          name_send.onclick = function() {
            socket.emit('set-name', name_box.value);
            name_msg.innerText = 'Already Sent';
            name_send.innerText = 'Sent';
            return name_send.onclick = function() {};
          };
          return name_box.onkeydown = function(e) {
            if (e.keyCode === 13) {
              name_send.onclick();
              return false;
            }
          };
        }
      };
    } else {
      return (get('name_box')).focus();
    }
  })();
  return clear.onclick = function() {
    topic_list = [];
    topic_store = {};
    return socket.emit('reload');
  };
};
